/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jacob' at '12/11/15 9:22 PM' with Gradle 2.9
 *
 * @author Jacob, @date 12/11/15 9:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
